#!/bin/bash
# In order to do it work, you can pass the a directory as argument.
# If the directory that you desire to count the txts is your current directory, you don't need to pass nothing!

directory=$1
txtFound=0

for i in $(ls $directory || .) 
do
	if [[ ${i: -3} == "txt" ]] 
	then
		((txtFound+=1))
		echo "Txt file found! \
		$i";
	fi;
done

echo "${txtFound} txts files found!"
